schema_version: 20180708
name: canny
version: 0.0.140
runtime: python
entrypoint: python3 canny.py
format: http-stream
memory: 1024
timeout: 60
triggers:
- name: canny-trigger
  type: http
  source: /canny-trigger
